"""Write a BookTree to a nested directory of markdown files."""

from __future__ import annotations
import sys
from pathlib import Path
from typing import TYPE_CHECKING

from shelf.models import BookTree, Section
from shelf.slugify import slugify

if TYPE_CHECKING:
    from shelf.summarize import SmartIndex

# Windows MAX_PATH is 260; reserve room for the prefix digits, separators, and .md
_MAX_PATH = 260 if sys.platform == "win32" else 1024


def write_shelf(
    tree: BookTree, output_dir: Path, smart_index: "SmartIndex | None" = None
) -> None:
    """Materialize the BookTree as a nested markdown directory.

    Layout:
      output_dir/
        INDEX.md          — linked TOC
        CLAUDE.md         — navigation instructions for coding agents
        01-chapter-slug/
          README.md       — H1 body content
          01-section-slug.md
          02-section-slug.md
          ...
        02-chapter-slug/
          ...
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    # Separate front matter from H1 chapters
    chapters = [s for s in tree.sections if s.title != "Front Matter"]
    front_matter = next((s for s in tree.sections if s.title == "Front Matter"), None)

    chapter_dirs: list[tuple[str, Path, Section]] = []  # (slug, dir_path, section)

    # Budget for slug lengths: total path must fit within _MAX_PATH.
    # Path structure: output_dir / "NN-<ch_slug>" / "NN-<sec_slug>.md"
    # Overhead: 2 seps + "NN-" prefix (3) + "NN-" prefix (3) + ".md" (3) = 11
    slug_budget = _MAX_PATH - len(str(output_dir)) - 11
    # Split budget evenly between chapter and section slugs (min 20 each)
    max_slug = max(slug_budget // 2, 20)

    for ch_idx, chapter in enumerate(chapters, start=1):
        ch_slug = slugify(chapter.title, max_length=max_slug) or f"chapter-{ch_idx}"
        ch_dir = output_dir / f"{ch_idx:02d}-{ch_slug}"
        ch_dir.mkdir(parents=True, exist_ok=True)
        chapter_dirs.append((ch_slug, ch_dir, chapter))

        # README.md — chapter's own body content
        readme_content = f"# {chapter.title}\n\n{chapter.content}\n"
        (ch_dir / "README.md").write_text(readme_content, encoding="utf-8")

        # H2 sections → individual .md files
        for sec_idx, section in enumerate(chapter.children, start=1):
            sec_slug = slugify(section.title, max_length=max_slug) or f"section-{sec_idx}"
            sec_file = ch_dir / f"{sec_idx:02d}-{sec_slug}.md"
            sec_content = _render_section(section)
            sec_file.write_text(sec_content, encoding="utf-8")

    # Write front matter to output root if present
    if front_matter:
        (output_dir / "front-matter.md").write_text(
            front_matter.content + "\n", encoding="utf-8"
        )

    # INDEX.md
    descriptions = smart_index.descriptions if smart_index else {}
    index_lines = [f"# {tree.title}\n", ""]
    for ch_idx, (ch_slug, ch_dir, chapter) in enumerate(chapter_dirs, start=1):
        ch_prefix = f"{ch_idx:02d}-{ch_slug}"
        ch_desc = descriptions.get(chapter.title, "")
        ch_link = f"- [{chapter.title}]({ch_prefix}/README.md)"
        index_lines.append(f"{ch_link} — {ch_desc}" if ch_desc else ch_link)
        for sec_idx, section in enumerate(chapter.children, start=1):
            sec_slug = slugify(section.title, max_length=max_slug) or f"section-{sec_idx}"
            sec_prefix = f"{sec_idx:02d}-{sec_slug}"
            sec_desc = descriptions.get(section.title, "")
            sec_link = f"  - [{section.title}]({ch_prefix}/{sec_prefix}.md)"
            index_lines.append(f"{sec_link} — {sec_desc}" if sec_desc else sec_link)
            # H3+ as anchor links
            for subsec in section.children:
                anchor = _to_anchor(subsec.title)
                index_lines.append(
                    f"    - [{subsec.title}]({ch_prefix}/{sec_prefix}.md#{anchor})"
                )
    index_lines.append("")
    (output_dir / "INDEX.md").write_text("\n".join(index_lines), encoding="utf-8")

    # CLAUDE.md
    chapter_count = len(chapters)
    section_count = sum(len(ch.children) for ch in chapters)
    subsection_count = sum(len(sec.children) for ch in chapters for sec in ch.children)

    claude_lines = [
        f"# {tree.title} — Navigation Guide",
        "",
        "This directory was generated by **shelf** and is designed for navigation by coding agents.",
        "",
    ]
    if smart_index and smart_index.overview:
        claude_lines += [
            "## Overview",
            "",
            smart_index.overview,
            "",
        ]
    claude_lines += [
        "## Structure",
        "",
        f"- **{chapter_count}** chapters (H1 → numbered directories)",
        f"- **{section_count}** sections (H2 → `.md` files inside each chapter directory)",
        f"- **{subsection_count}** subsections (H3 → headings within section files)",
        "",
        "## How to navigate",
        "",
        "- `INDEX.md` — full linked table of contents",
        "- Each chapter is a directory: `01-chapter-name/`",
        "- Each section is a file: `01-chapter-name/01-section-name.md`",
        "- Chapter overview: `01-chapter-name/README.md`",
        "",
        "## Grep hints",
        "",
        "```bash",
        "# Find all section headings",
        f'grep -r "^## " {output_dir.name}/',
        "",
        "# Search for a topic",
        f'grep -rl "due process" {output_dir.name}/',
        "",
        "# List all chapters",
        f"ls {output_dir.name}/",
        "```",
        "",
        "## Statistics",
        "",
        f"- Chapters: {chapter_count}",
        f"- Sections: {section_count}",
        f"- Subsections: {subsection_count}",
        f"- Source: {tree.source_path.name if tree.source_path else 'unknown'}",
        "",
    ]
    (output_dir / "CLAUDE.md").write_text("\n".join(claude_lines), encoding="utf-8")


def _render_section(section: Section) -> str:
    """Render an H2 section and its H3+ children as a single markdown file."""
    parts = [f"## {section.title}\n\n{section.content}"]
    for subsec in section.children:
        parts.append(_render_subsection(subsec, base_level=3))
    return "\n\n".join(parts) + "\n"


def _render_subsection(section: Section, base_level: int) -> str:
    hashes = "#" * base_level
    parts = [f"{hashes} {section.title}\n\n{section.content}"]
    for child in section.children:
        parts.append(_render_subsection(child, base_level + 1))
    return "\n\n".join(parts)


def _to_anchor(title: str) -> str:
    """Convert a heading title to a GitHub-style markdown anchor."""
    import re

    anchor = title.lower()
    anchor = re.sub(r"[^\w\s-]", "", anchor)
    anchor = re.sub(r"\s+", "-", anchor)
    return anchor.strip("-")
